### ISSUE TITLE
VPM Config | Correction

### ISSUE THREAD

**Issue by Adios-official** [f5devcentral/f5-xc-tf-modules#3]
The  Value of CloudProvider needs to be "disabled" instead of null string "" within the vpm_config :
location : f5xc/ce/aws/config/locals.tf

Preferred code : 
 Kubernetes = {
      Server        = var.f5xc_ce_hosts_public_name
      EtcdUseTLS    = true
      CloudProvider = "disabled"
    }

Post code change, the config worked for me and services came up.

Until then The services were not starting within the CEs and resulted in below state :
Aug 08 16:04:59 ip-10-10-1-78.eu-central-1.compute.internal vpm[8199]: workload.go:268: Object from app coredns: coredns *k8s.DeploymentObject is in status: Failed, replicas are not in desired state, required replicas: 1, current replicas: 0

**Comment by Adios-official** [comment]
@cklewar  After upgrade this seems to have changed again. I cannot say for other providers. But for AWS, this is what works now :
Preferred code :
Kubernetes = {
Server = var.f5xc_ce_hosts_public_name
EtcdUseTLS = true
}

CloudProvider is no longer needed in the code.

**Comment by Adios-official** [comment]
@cklewar Changes to the above can be halted as after new VPM release, there are further changes needed to the value of CloudProvider = "disabled" or logical corrections needed in VPM code.

**Comment by cklewar** [comment]
@Adios-official thx. Removed `CloudProvider = "disabled"` from config module.
