### ISSUE TITLE
HTTP Proxy in VPM_Config

### ISSUE THREAD

**Issue by Adios-official** [f5devcentral/f5-xc-tf-modules#4]
Is it possible to add a variable / option to pass HTTP Proxy to the VPM config ? this would help to have HTTP proxy configured at the boot time itself. My customer has allowed the IPs/Domains for Site provisioning in the HTTP Proxy so it would be good to have the HTTP proxy value to be passed in via the TF code itself.

**Comment by cklewar** [comment]
exposed proxy variables for vpm config. Find example at: https://github.com/f5devcentral/terraform-xc-aws-ce/blob/main/examples/single_node_single_nic_new_vpc_new_subnet_proxy/README.md
